name: vEnderChests
version: '${project.version}'
main: club.vertuli.venderchests.vEnderChests
commands:
  enderchest:
    description: Otwiera enderchest
    aliases:
      - ec
    usage: /enderchest
  venderchest:
      description: Glowna komenda pluginu vEnderChests
      aliases:
        - vec
      usage: /venderchest